"""add session_id to ai_chats

Revision ID: f80adb4bcdcc
Revises: b23320b358fb
Create Date: 2026-07-21 11:54:46.953363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f80adb4bcdcc'
down_revision: Union[str, Sequence[str], None] = 'b23320b358fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_chats', sa.Column('session_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_ai_chats_session_id'), 'ai_chats', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_chats_session_id'), table_name='ai_chats')
    op.drop_column('ai_chats', 'session_id')
    # ### end Alembic commands ###
